Mis_Perris_Usuarios/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('Usuario.urls')),
    url(r'^accounts/', include('accounts.urls'))
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Usuario/urls.py
from django.conf.urls import include , url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', views.formulario, name='formulario'),
    path('Usuario/new', views.reg_new, name='reg_new'),
    path('Usuario/list',views.listar),
    path('Usuario/man', views.reg_masc, name='reg_masc'),
    path('Usuario/manlist', views.masclist, name='masclist'),
    path('update/<int:id>/', views.update_mascota, name="update_mascota"),
    path('delete/<int:id>/', views.delete_mascota, name="delete_mascota"),
    path('Usuario/manlist2', views.listar_resc, name='rescatados'),
    path('Usuario/manlist3', views.listar_adop, name='adoptados'),
    path('Usuario/manlist4', views.listar_disp, name='disponibles'),
    path('Usuario/servicio', views.servicio, name='servicio')
    
]

accounts/urls.py
from django.conf.urls import url
from . import views


app_name = 'accounts'

urlpatterns=[
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^recuperar/$', views.recup, name="recup"),
    url(r'^mensaje/$', views.men, name="men"),
]

Usuario/models.py
from django.db import models

# Create your models here.
class Usuario(models.Model):
    correo = models.CharField(max_length=40)
    rut = models.CharField(max_length=11)
    nombre = models.CharField(max_length=40)
    fechaN = models.DateField()
    telefono = models.IntegerField()
    region =  models.CharField(max_length=40)
    ciudad =  models.CharField(max_length=40)
    tipoCasa =  models.CharField(max_length=40)

    def guardar(self):
        self.save()
    
    def __str__(self):
        return self.nombre

class Mascota(models.Model):
    fotografia = models.ImageField(upload_to='fotos/')
    nombre = models.CharField(max_length=40)
    razaPredominante = models.CharField(max_length=40)
    descripcion = models.TextField()
    estado = models.CharField(max_length=20)


    def guardar(self):
        self.save()
    
    def __str__(self):
        return self.nombre

accounts/models.py
from django.db import models

# Create your models here.

Usuario/forms.py
from django import forms

from .models import Usuario, Mascota

class RegForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ('correo', 'rut', 'nombre', 'fechaN','telefono', 'region', 'ciudad', 'tipoCasa')


class MascForm(forms.ModelForm):
    fotografia = forms.ImageField()
    class Meta:
        model = Mascota
        fields = (
            'fotografia',
            'nombre',
            'razaPredominante',
            'descripcion',
            'estado',
        )

Usuario/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.template import RequestContext
from .models import Usuario, Mascota
from .forms import RegForm, MascForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

def formulario(request):
    return render(request, 'misperris/Main.html')

@login_required(login_url="/accounts/login/")
def reg_new(request):
    
    if request.method == "POST":
        
        form = RegForm(request.POST)
        if form.is_valid():
            form.save()
            '''Usuarios = Usuario.objects.all()
            return render(request, 'misperris/list.html', {'lista': Usuarios})'''
            return redirect('servicio')
    else:
        form = RegForm()
        return render(request, 'misperris/formulario.html', {'form': form})

@login_required(login_url="/accounts/login/")
def listar(request):
    Usuarios = Usuario.objects.all().orderby('nombre')
    return render(request, 'misperris/list.html', {'lista': Usuarios})

@login_required(login_url="/accounts/login/")
def reg_masc(request):
    if request.method == "POST":
        form = MascForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            form.save()
            mascotas = Mascota.objects.all()
            return render(request, 'misperris/manlist.html', {'listam': mascotas})
    else:
        form = MascForm()
        return render(request, 'misperris/mantenedor.html', {'form': form})
    
@login_required(login_url="/accounts/login/")
def masclist(request):
    mascotas = Mascota.objects.all()
    return render(request, 'misperris/manlist.html', {'listam': mascotas})

@login_required(login_url="/accounts/login/")
def update_mascota(request, id):
    mascota = Mascota.objects.get(id=id)
    form = MascForm(request.POST or None, instance=mascota)
    print(mascota.nombre)
    if form.is_valid():
        form.save()
        mascotas = Mascota.objects.all()
        return render(request, 'misperris/manlist.html', {'listam': mascotas})
    
    return render(request, 'misperris/mantenedor.html', {'mascota': mascota}) 

@login_required(login_url="/accounts/login/")
def delete_mascota(request, id):
    mascota = Mascota.objects.get(id=id)

    if request.method == 'POST':
        mascota.delete()
        mascotas = Mascota.objects.all()
        return render(request, 'misperris/manlist.html', {'listam': mascotas})

    return render(request, 'misperris/confirmacion.html', {'mascota': mascota})

@login_required(login_url="/accounts/login/")
def listar_resc(request):
    mascotas = Mascota.objects.all().filter(estado='Rescatado')
    return render(request, 'misperris/manlist2.html', {'listam': mascotas})

@login_required(login_url="/accounts/login/")
def listar_adop(request):
    mascotas = Mascota.objects.all().filter(estado='Adoptado')
    return render(request, 'misperris/manlist3.html', {'listam': mascotas})

@login_required(login_url="/accounts/login/")
def listar_disp(request):
    mascotas = Mascota.objects.all().filter(estado='Disponible')
    return render(request, 'misperris/manlist4.html', {'listam': mascotas})

@login_required(login_url="/accounts/login/")
def servicio(request):
    return render(request, 'misperris/servicio.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request, user)
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('formulario')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('formulario')

def recup(request):
    if request.method == 'POST':
        return redirect('accounts:men')
    return render(request, 'accounts/recuperar.html')
    
def men(request):
    return render(request, 'accounts/men.html')

Usuario/templates/misperris/Main.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
    <head>
        <meta charset="utf-8">
        <title> MIS PERRIS</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'js/slick/slick.css' %}">
        <link rel="stylesheet" href="{% static 'js/slick/slick-theme.css' %}">
        <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
        <script src="{% static 'js/jquery-latest.js' %}"></script>
        <script src="{% static 'js/slick/slick.min.js' %}"></script>
    </head>
    <body>
        <div class="container1">
            <div class="anch">
                <div class="box1">
                        <img id="logo" src="{% static 'images/logo.png' %}" alt="">
                </div>
            
                <div class="box2">
                        <nav class="menu">
                                <ul>
                                    <li class="l"><a href="{% url 'formulario' %}">Inicio</a></li>
                                    {% if not user.is_active %}
                                    <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                    {% endif %}
                                    <li class="l"><a href="{% url 'servicio' %}">Servicios</a></li>
                                    {% if user.is_active %}
                                        <li class="l"><a href="">{{user.username}}</a></li>
                                    {% else %}
                                        <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                    {% endif %}
                                </ul>
                        </nav>
                </div>
            </div>
                <div class="slick">
                    <div class="slide slide1">
                        <img class="carr" src="{% static 'images/adoptados/Apolo.jpg' %}" alt="">
                        <div id= "t">
                                <h6>
                                "Estamos felices
                                <br>
                                de tener a Apolo en
                                <br>
                                casa. Es un super
                                <br>
                                fiel compañero"
                                </h6>
                        </div>
                    </div>
                    <div class="slide slide2">
                        <img class="carr"  src="{% static 'images/adoptados/Tom.jpg' %}" alt="">
                        <div id= "t1">
                            <h6>
                            "Estamos felices
                            <br>
                            de tener a Tom en
                            <br>
                            casa. Es un super
                            <br>
                            fiel compañero"
                            </h6>
                        </div>
                    </div>
                    <div class="slide slide3">
                        <img class="carr" src="{% static 'images/adoptados/Duque.jpg' %}"  alt="">
                        <div id= "t2">
                            <h6>
                                "Estamos felices
                                <br>
                                de tener a Duque en
                                <br>
                                casa. Es un super
                                <br>
                                fiel compañero"
                                </h6>
                        </div>
                    </div>
                </div>
                <script>
                    $(".slick").slick({
                        dots: true,
                        fade: true,
                        arrows: true,
                        autoplay: true 
                    }    
                    ) ;
                </script>
                <div class="sub">
                <div id="ws"> +56998765431</div>
                <div id="tit"> Rescate y adopción de perritos callejeros </div>
                <div class="redes">
                    <img src="{% static 'images/fb.png' %}" alt="">
                    <img src="{% static 'images/google.png' %}" alt="">
                    <img src="{% static 'images/insta.png' %}" alt="">
                    <img src="{% static 'images/mail.png' %}" alt="">

                </div>
                </div>
                
            </div>
            <div class="container2">
                <div class="articulo1">
                        <h4>RESCATE</h4>
                        <H6>ETAPA UNO</H6>
                        <h6>_______</H6>
                        <br>
                        <p>Rescatamos perritos en situación de peligro y/o abandono. Los rehabilitamos y los</p>
                        <p>preparamos para buscarles un hogar.</p>
                        <br>
                        <img src="{% static 'images/rescate.jpg' %}" alt="">
                </div>
                <div class="articulo2">
                        <img src="{% static 'images/crowfunding.jpg' %}" alt="">
                        <h4>CROWDFUNDING</h4>
                        <h6>FINANCIAMIENTO</h6>
                        <h6>_______</h6>
                        <br>
                        <p>Sigue nuestras redes sociales para informarte acerca de las diversas campañas y</p>
                        <p>actividades que realizamos para obtener financiamiento para seguir ayudando.</p>
                        <br>
                        <input type="button" value="CAMPAÑAS">
                </div>
            </div>
            <div class="galeria">
                <a href="{% static 'images/rescatados/Oso.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Oso, soy un perrito de baja estatura muy jugueton y regalon.">
                    <img src="{% static 'images/rescatados/Oso_tn.jpg' %}" alt=""></a>
                <a href="{% static 'images/rescatados/Maya.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Maya, soy una cachorrita de color cafe, de pelaje liso, llena de energia y cariñosa.">
                    <img src="{% static 'images/rescatados/Maya_tn.jpg' %}" alt=""></a>
                <a href="{% static 'images/rescatados/Wifi.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Wifi, soy un perro pequeño, dormilon y muy regalon.">
                    <img src="{% static 'images/rescatados/Wifi_tn.jpg' %}" alt=""></a>
                <a href="{% static 'images/rescatados/Chocolate.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Chocolate, soy un perro grande de pelaje liso muy bueno para correr y jugar.">
                    <img src="{% static 'images/rescatados/Chocolate_tn.jpg' %}" alt=""></a>
                <a href="{% static 'images/rescatados/Pexel.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Pexel, soy un perrito pequeño de pelaje mediano muy regalon y jugueton.">
                    <img src="{% static 'images/rescatados/Pexel_tn.jpg' %}" alt=""></a>
                <a href="{% static 'images/rescatados/Bigotes.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Bigotes, soy un perro adulto de pelaje mediano, soy muy jugueton y me gusta salir a pasear.">
                    <img src="{% static 'images/rescatados/Bigotes_tn.jpg' %}" alt=""></a>
                <a href="{% static 'images/rescatados/Luna.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Luna, soy una cachorrita de pelaje oscuro y corto, soy muy regalona y me gusta estar en casa.">
                    <img src="{% static 'images/rescatados/Luna_tn.jpg' %}" alt=""></a>
                <script src="{% static 'js/lightbox-plus-jquery.min.js' %}"></script>
            </div>
           <div class="pie">
               <footer>
                   <h5>Desarrollo Web y Mobile</h5>
                {% if user.is_active %}
                    <form action="{% url 'accounts:logout' %}" method="post"> {% csrf_token %}
                        <button type="submit" id="logout">Cerrar Sesión</button>
                    </form>  
                   <h5 id="cone">Conectado como {{user.username}}</h5>
                {% endif %}
               </footer>
           </div>
    </body>
</html>

Usuario/templates/misperris/manlist.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/estilo2.css' %}" />
    <title>Document</title>
</head>
<body>
        <div class="anch">
                <div class="box1">
                        <img id="logo" src="{% static 'images/logo.png' %}" alt="">
                </div>
            
                <div class="box2">
                        <nav class="menu">
                                <ul>
                                    <li class="l"><a href="{% url 'formulario' %}">Inicio</a></li>
                                    {% if not user.is_active %}
                                    <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                    {% endif %}
                                    <li class="l"><a href="{% url 'servicio' %}">Servicios</a></li>  
                                    {% if user.is_active %}
                                    <li class="l"><a href="">{{user.username}}</a></li>
                                    {% else %}
                                    <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                    {% endif %}
                                </ul>
                        </nav>
                </div>
            </div>
    <div class="borde">
        <h1>Lista Mascotas</h1>
        {% for perro in listam %}
        <div>
                <a href="{% url 'update_mascota' perro.id %}">
                        <img src="{{ perro.fotografia.url }}" alt="">
                        <br></a> 
                        <h4>Nombre: {{perro.nombre}}</h4>
                        <h4>Raza predominante: {{perro.razaPredominante}}</h4>
                        <h4> Descripcion: {{perro.descripcion}}</h4>
                        <h4>Estado: {{perro.estado}}</h4>
                   
                
                <br>
        </div>
        {% endfor %}

        {% if request.user.is_superuser %}
                <a href="{% url 'reg_masc' %}">Agregar nuevo</a>
                <br>
                <a href="{% url 'rescatados' %}">Ver rescatados</a>
                <a href="{% url 'adoptados' %}">Ver adoptados</a>
                <a href="{% url 'disponibles' %}">Ver disponibles</a>
        {% else %}
                <a href="{% url 'disponibles' %}">Ver disponibles</a>
        {% endif %}
       
    </div>
    <div class="pie">
                <footer>
                 {% if user.is_active %}
                     <form method="POST" action="{% url 'accounts:logout' %}">
                         {% csrf_token %}
                         <h5>Conectado Como {{user.username}}</h5>
                         <br>
                         <button type="submit" >Cerrar Sesión</button>
                         
                     </form>
                 {% endif %}
                </footer>
     </div>
    

   
</body>
</html>

Usuario/templates/misperris/manlist2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/estilo2.css' %}" />
    <title>Document</title>
</head>
<body>
        <div class="anch">
                <div class="box1">
                        <img id="logo" src="{% static 'images/logo.png' %}" alt="">
                </div>
            
                <div class="box2">
                        <nav class="menu">
                                <ul>
                                    <li class="l"><a href="{% url 'formulario' %}">Inicio</a></li>
                                    {% if not user.is_active %}
                                    <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                    {% endif %}
                                    <li class="l"><a href="{% url 'servicio' %}">Servicios</a></li> 
                                    {% if user.is_active %}
                                    <li class="l"><a href="">{{user.username}}</a></li>
                                    {% else %}
                                    <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                    {% endif %}
                                </ul>
                        </nav>
                </div>
            </div>
            <div class="borde">
                        <h1>Lista Rescatados</h1>
                        {% for perro in listam %}
                        <div>
                             <a href="{% url 'update_mascota' perro.id %}">
                                    <img src="{{ perro.fotografia.url }}" alt="">
                                    <br></a> 
                                    <h4>Nombre: {{perro.nombre}}</h4>
                                    <h4>Raza predominante: {{perro.razaPredominante}}</h4>
                                    <h4> Descripcion: {{perro.descripcion}}</h4>
                                    <h4>Estado: {{perro.estado}}</h4>
                                
                            
                            <br>
                        </div>
                        {% endfor %}
                    
                        <a href="{% url 'masclist' %}">Volver Atras</a>
            </div>
            <div class="pie">
                        <footer>
                         {% if user.is_active %}
                             <form method="POST" action="{% url 'accounts:logout' %}">
                                 {% csrf_token %}
                                 <h5>Conectado Como {{user.username}}</h5>
                                 <br>
                                 <button type="submit" >Cerrar Sesión</button>
                                 
                             </form>
                         {% endif %}
                        </footer>
             </div>
    
</body>
</html>

Usuario/templates/misperris/manlist3.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/estilo2.css' %}" />
    <title>Document</title>
</head>
<body>
        <div class="anch">
                <div class="box1">
                        <img id="logo" src="{% static 'images/logo.png' %}" alt="">
                </div>
            
                <div class="box2">
                        <nav class="menu">
                                <ul>
                                    <li class="l"><a href="{% url 'formulario' %}">Inicio</a></li>
                                    {% if not user.is_active %}
                                    <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                    {% endif %}
                                    <li class="l"><a href="{% url 'servicio' %}">Servicios</a></li>  
                                    {% if user.is_active %}
                                    <li class="l"><a href="">{{user.username}}</a></li>
                                    {% else %}
                                    <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                    {% endif %}
                                </ul>
                        </nav>
                </div>
            </div>
            <div class="borde">
                        <h1>Lista Adoptados</h1>
                        {% for perro in listam %}
                        <div>
                             <a href="{% url 'update_mascota' perro.id %}">
                                    <img src="{{ perro.fotografia.url }}" alt=""> 
                                    <br></a>
                                    <h4>Nombre: {{perro.nombre}}</h4>
                                    <h4>Raza predominante: {{perro.razaPredominante}}</h4>
                                    <h4> Descripcion: {{perro.descripcion}}</h4>
                                    <h4>Estado: {{perro.estado}}</h4>
                                
                            
                            <br>
                        </div>
                        {% endfor %}
                    
                        <a href="{% url 'masclist' %}">Volver Atras</a>
            </div>
            <div class="pie">
                        <footer>
                         {% if user.is_active %}
                             <form method="POST" action="{% url 'accounts:logout' %}">
                                 {% csrf_token %}
                                 <h5>Conectado Como {{user.username}}</h5>
                                 <br>
                                 <button type="submit" >Cerrar Sesión</button> 
                                 
                             </form>
                         {% endif %}
                        </footer>
             </div>
   
</body>
</html>

Usuario/templates/misperris/manlist4.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/estilo2.css' %}" />
    <title>Document</title>
</head>
<body>
        <div class="anch">
                <div class="box1">
                        <img id="logo" src="{% static 'images/logo.png' %}" alt="">
                </div>
            
                <div class="box2">
                        <nav class="menu">
                                <ul>
                                    <li class="l"><a href="{% url 'formulario' %}">Inicio</a></li>
                                    {% if not user.is_active %}
                                    <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                    {% endif %}
                                    <li class="l"><a href="{% url 'servicio' %}">Servicios</a></li>  
                                    {% if user.is_active %}
                                    <li class="l"><a href="">{{user.username}}</a></li>
                                    {% else %}
                                    <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                    {% endif %}
                                </ul>
                        </nav>
                </div>
            </div>
            <div class="borde">
                        <h1>Lista Disponibles</h1>
                        {% for perro in listam %}
                        <div>
                            {% if request.user.is_superuser %}
                             <a href="{% url 'update_mascota' perro.id %}">
                                    <img src="{{ perro.fotografia.url }}" alt=""> 
                                    <br>
                             </a>
                             <h4>Nombre: {{perro.nombre}}</h4>
                             <h4>Raza predominante: {{perro.razaPredominante}}</h4>
                             <h4> Descripcion: {{perro.descripcion}}</h4>
                             <h4>Estado: {{perro.estado}}</h4>
                            {% else %}
                             <a href="{% url 'reg_new' %}">
                                    <img src="{{ perro.fotografia.url }}" alt=""> 
                                    <br>
                             </a>
                             <h4>Nombre: {{perro.nombre}}</h4>
                             <h4>Raza predominante: {{perro.razaPredominante}}</h4>
                             <h4> Descripcion: {{perro.descripcion}}</h4>
                             <h4>Estado: {{perro.estado}}</h4>
                            {% endif %}
                            
                            <br>
                        </div>
                        {% endfor %}
                    
                        {% if request.user.is_superuser %}
                        <a href="{% url 'masclist' %}">Volver Atras</a>
                        {% else %}
                        <a href="{% url 'servicio' %}">Volver Atras</a>
                        {% endif %}
            </div>
            <div class="pie">
                        <footer>
                         {% if user.is_active %}
                             <form method="POST" action="{% url 'accounts:logout' %}">
                                 {% csrf_token %}
                                 <h5>Conectado Como {{user.username}}</h5>
                                 <br>
                                 <button type="submit" >Cerrar Sesión</button>
                                 
                             </form>
                         {% endif %}
                        </footer>
             </div>
    
</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/estilo2.css' %}" />
    <title>registro</title>
</head>
<body>


<div class="anch">
    <div class="box1">
                <img id="logo" src="{% static 'images/logo.png' %}" alt="">
        </div>
    
        <div class="box2">
                <nav class="menu">
                        <ul>
                            <li class="l"><a href="{% url 'formulario' %}">Inicio</a></li>
                            <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                            <li class="l"><a href="{% url 'servicio' %}">Servicios</a></li>  
                            <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                        </ul>
                </nav>
        </div>
    </div>

    <div class="borde">
        
            <h1>Iniciar Sesión</h1>
        
            <form method="POST" >
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <br>
                <br>
                <a href="{%  url 'accounts:recup' %}">¿Has olvidado tu contraseña?</a>
                <br>
                <a href="{% url 'accounts:signup' %}">Registrate</a>
                <br>
                <br>
                <input type="submit" value="Login"> 
                  
            </form>
        
        
    </div>
   

</div>
   
</body>
</html>